### ISSUE TITLE
APP发布后如果用这个收集堆栈信息，在使用符号表解析可以吗

### ISSUE THREAD

**Issue by ganvinalix** [bestswifter/BsBacktraceLogger#3]
APP发布后如果用这个收集堆栈信息，在使用符号表解析可吗？解析后内容准确吧。

**Comment by bestswifter** [comment]
据我所知不行，苹果为了优化，在 release 模式下，符号名不是存在内存里，而是磁盘中。这也就是很多第三方 crash 统计平台要求上传 dSYM 文件的原因

**Comment by bestswifter** [comment]
先 close 了，如果后续有问题可以再提 issue
